config/routes.rb
Rails.application.routes.draw do
  resources :videos

  get 'pages/about'

  get 'pages/contact'

    root 'videos#index'

end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
      @videos = Video.all
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
        params.require(:video).permit(:wistia, :description, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Code4Newbies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
      <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/js/materialize.min.js"></script>

</head>
<body>

      <nav>
    <div class="nav-wrapper">
        <%= link_to "Code4Newbies", root_path, :class => "brand-logo" %>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="<%= root_path %>"><i class="mdi-action-view-list"></i></a></li>
        <li><a href="<%= pages_about_path %>"><i class="mdi-action-perm-identity"></i></a></li>
        <li><a href="<%= pages_contact_path %>"><i class="mdi-maps-place"></i></a></li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="<%= root_path %>"><i class="mdi-action-view-list"></i></a></li>
        <li><a href="<%= pages_about_path %>"><i class="mdi-action-perm-identity"></i></a></li>
        <li><a href="<%= pages_contact_path %>"><i class="mdi-maps-place"></i></a></li>
      </ul>
    </div>
  </nav>
<div class="row">
    <div class="col m10 offset-m1">
        <%= yield %>
    </div>
</div>

    <script>$(".button-collapse").sideNav();</script>
</body>
</html>

app/views/pages/about.html.erb
<h1>About me</h1>
<div class="card z-depth-3">
    <div class="card-content whitetext">
        <div class="col m6">
        <a class="twitter-timeline" href="https://twitter.com/fupuchu" data-widget-id="598756902869204992">Tweets by @fupuchu</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
        </div>
        <div class="col m6">
            <div class="card-panel grey lighten-3 z-depth-1">
                <div class="row valign-wrapper">
                    <div class="col m3">
                        <%= image_tag "avatar.jpg", class: "circle responsive-img" %>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

app/views/pages/contact.html.erb
<h3>Contact</h3>

<div class="card z-depth 3">
    <div class="card-content">
        <p>Want to look for me? Check out my office on Maps!</p>
        <br>
        <div id="map-canvas"></div>
    </div>
</div>

<style>
      #map-canvas {
        width: 100%;
        height: 400px;
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script>
      function initialize() {
        var mapCanvas = document.getElementById('map-canvas');
        var mapOptions = {
          center: new google.maps.LatLng(1.333214, 103.892177),
          zoom: 8,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(mapCanvas, mapOptions)
        var marker = new google.maps.Marker({
            position: new google.maps.LatLng(1.333214, 103.892177),
            title: "Here is Singapore!"
        });
          marker.setMap(map);
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="input-field">
    <%= f.text_field :wistia, :placeholder => 'Link', :length => '10' %>
</div>
<div class="input-field">
    <%= f.text_field :title, :placeholder => 'Title', :length => '20' %>
</div>
<div class="input-field">
      <%= f.text_field :description, :placeholder => 'Description', :length => '800', :class => 'materialize-textarea' %>
</div>
<button class="btn waves-effect waves-light" type="submit" name="action">Submit</button>
<a href="<%= videos_path %>" class="btn waves-effect waves-light" name="action">Back</a>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>
<div class="card">
    <div class="card-content">
        <%= render 'form' %>
    </div>
</div>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Videos</h1>

<%= link_to new_video_path, :class => 'btn-floating btn-large waves-effect waves-light red' do %>
    <i class="mdi-content-add"></i>
<% end %>

<ul class="collapsible" data-collapsible="accordion">
    <% @videos.each do |video| %>
        <li>
            <div class="collapsible-header">
                <i class="mdi-av-my-library-books"></i>
                <%= link_to video.title, video %>
                <span class="right">
                    <%= link_to edit_video_path(video) do %>
                    <i class="mdi-content-create"></i><% end %>
                    <%= link_to video, method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <i class="mdi-notification-event-busy"></i><% end %>
                </span>
            </div>
            <div class="collapsible-body"><p><%= video.description %></p></div>
        </li>
    <% end %>
</ul>

app/views/videos/new.html.erb
<h1>New Video</h1>
<div class="card">
    <div class="card-content">
        <%= render 'form' %>
    </div>
</div>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <div class="col m3">
      <div class="collection">
          <% @videos.each do |video| %>
          <%= link_to video.title, video, :class => 'collection-item' %>
          <% end %>
      </div>
    </div>
    <div class="col m9">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
                <span class="card-title"><%= @video.title %></span>
                <p><%= @video.description %></p>
            </div>
            <div class="card-action">
              <a href="#">Previous</a>
                <span class="right">
              <a href='#'>Next</a>
                </span>
            </div>
          </div>
        </div>
      </div>